# Generated by Django 3.2.18 on 2023-05-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230525_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes_users',
        ),
    ]
