# Generated by Django 3.2.18 on 2023-05-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_likes_users'),
        ('accounts', '0002_user_likes_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes_users',
        ),
        migrations.AddField(
            model_name='user',
            name='likes_movies',
            field=models.ManyToManyField(related_name='likes_user', to='movies.Movie'),
        ),
    ]
